import Phaser from 'phaser';
import { io, Socket } from 'socket.io-client';
import { AgentData, SceneInitData, WorldUpdate, TILE_SIZE, TICK_DURATION, ChatMessage, PartialMessage, ConversationStreamEventDetail } from '../types';
import { JOB_SKINS, JobRole } from '../src/config/JobRegistry';
import { getCharacterByJob, getCharacterById, CHARACTER_REGISTRY, CharacterDefinition } from '../src/config/CharacterRegistry';
import { EnvironmentManager } from '../src/game/EnvironmentManager';
import { EnvironmentRenderer } from '../src/game/EnvironmentRenderer';
import { CollisionManager } from '../src/game/CollisionManager';
import { ConversationDirector } from '../src/game/ConversationDirector';
import { sanitizeMessage, sanitizeError } from '../src/utils/sanitize';

export class MainScene extends Phaser.Scene {
  private socket: Socket | null = null;
  private agents: Map<string, Phaser.GameObjects.Sprite> = new Map();
  private agentNameTags: Map<string, Phaser.GameObjects.Text> = new Map();
  private agentShadows: Map<string, Phaser.GameObjects.Graphics> = new Map();
  private onAgentSelect?: (agent: AgentData) => void;
  private onConversationUpdate?: (detail: ConversationStreamEventDetail) => void;
  private cursors?: Phaser.Types.Input.Keyboard.CursorKeys;
  
  // Store latest data to handle click selection
  private agentsDataStore: Map<string, AgentData> = new Map();

  // Environment System
  private environmentManager?: EnvironmentManager;
  private environmentRenderer?: EnvironmentRenderer;
  private collisionManager?: CollisionManager;
  
  // Conversation System
  private conversationDirector?: ConversationDirector;

  // Mock Simulation State
  private useMockData = true; // Set to true to see the world without a backend
  private mockTickTimer?: Phaser.Time.TimerEvent;
  private mockAgents: AgentData[] = []; // Persistent mock agents array for agent creation
  
  // Zoom State
  private currentZoom = 2;
  private minZoom = 1;
  private maxZoom = 4;
  private zoomSpeed = 0.1;
  private zoomUI?: Phaser.GameObjects.Text;

  constructor() {
    super({ key: 'MainScene' });
  }

  init(data: SceneInitData) {
    this.onAgentSelect = data.onAgentSelect;
    this.onConversationUpdate = data.onConversationUpdate;
  }

  preload() {
    // Helper to safely load images only if they don't exist
    const loadImage = (key: string, path: string) => {
        if (!this.textures.exists(key)) {
            this.load.image(key, path);
        }
    };

    // Helper to safely load spritesheets only if they don't exist
    const loadSpritesheet = (key: string, path: string, config: Phaser.Types.Loader.FileTypes.ImageFrameConfig) => {
        if (!this.textures.exists(key)) {
            this.load.spritesheet(key, path, config);
        }
    };

    // Load new pixel art assets if they exist (generated by tools/generate-assets.ts)
    // Environment assets now in /assets/environment/
    loadImage('grass_tileset', '/assets/environment/grass_tileset.png');
    loadImage('path_tileset', '/assets/environment/path_tileset.png');
    loadImage('building-OFFICE', '/assets/environment/building-office.png');
    loadImage('building-HOSPITAL', '/assets/environment/building-hospital.png');
    loadImage('building-CAFE', '/assets/environment/building-cafe.png');
    loadImage('building-LIBRARY', '/assets/environment/building-library.png');
    loadImage('building-LAB', '/assets/environment/building-lab.png');
    loadImage('building-WAREHOUSE', '/assets/environment/building-warehouse.png');
    loadImage('building-HOUSE', '/assets/environment/building-house.png');
    loadImage('building-STORAGE', '/assets/environment/building-storage.png');
    loadImage('building-PARK_BENCH', '/assets/environment/building-park-bench.png');
    loadImage('building-FOUNTAIN', '/assets/environment/building-fountain.png');

    // Load atlases as fallback or for dynamic characters
    loadSpritesheet('minions_atlas', '/assets/minions_atlas.png', { 
        frameWidth: 32, 
        frameHeight: 32 
    });
    
    loadSpritesheet('buildings_atlas', '/assets/buildings_atlas.png', { 
        frameWidth: 32, 
        frameHeight: 32 
    });
    
    loadSpritesheet('plants_props_atlas', '/assets/plants_props_atlas.png', { 
        frameWidth: 32, 
        frameHeight: 32 
    });

    // Load the character sprite sheet.
    loadSpritesheet('agent_atlas', '/assets/jobs_atlas.png', { 
      frameWidth: 32, 
      frameHeight: 32 
    });
    
    // Custom Characters in /assets/custom/
    loadImage('custom_shadow_knight', '/assets/custom/shadow_knight.png');
    loadImage('custom_batman', '/assets/custom/batman.png');
    loadImage('custom_sage', '/assets/custom/sage.png');
    loadImage('custom_agent', '/assets/custom/agent.png');
    
    loadImage('tileset', 'https://labs.phaser.io/assets/tilemaps/tiles/super-mario.png'); // Placeholder tiles
  }

  create() {
    this.events.on(Phaser.Scenes.Events.SHUTDOWN, this.shutdownScene, this);
    this.events.on(Phaser.Scenes.Events.DESTROY, this.shutdownScene, this);

    // Listen for agent creation events from React
    window.addEventListener('create-agent', this.handleCreateAgentEvent as EventListener);
    // Listen for chat start events
    window.addEventListener('start-chat', this.handleStartChatEvent as EventListener);

    // Initialize Conversation Director
    this.conversationDirector = new ConversationDirector(this, (detail) => {
        if (this.onConversationUpdate) {
            this.onConversationUpdate(detail);
        }
    });

    this.createWorld();
    this.setupSocket(); // Socket passed to director inside here
    this.setupInput();
    this.setupZoomControls();

    // Generate fallback textures if assets failed to load
    if (!this.textures.exists('characters')) {
        this.createFallbackTextures();
    }

    // Camera Setup
    this.cameras.main.setZoom(2);
    this.cameras.main.centerOn(600, 450); // Center on middle of 40x30 map
    this.cameras.main.setBackgroundColor('#3a5a3a'); 
    
    // Add post-processing effects for visual polish
    this.addPostProcessingEffects();

    if (this.input.keyboard) {
        this.cursors = this.input.keyboard.createCursorKeys();
    }

    // Start Mock Simulation if enabled
    if (this.useMockData) {
        this.startMockSimulation();
    }
  }

  update(time: number, delta: number) {
      // 1. Camera Movement from Keyboard
      const cameraSpeed = 10;
      if (this.cursors) {
          if (this.cursors.left.isDown) this.cameras.main.scrollX -= cameraSpeed;
          if (this.cursors.right.isDown) this.cameras.main.scrollX += cameraSpeed;
          if (this.cursors.up.isDown) this.cameras.main.scrollY -= cameraSpeed;
          if (this.cursors.down.isDown) this.cameras.main.scrollY += cameraSpeed;
      }

      // 2. Update Conversation Director (handles mock typing, timeouts)
      if (this.conversationDirector) {
          // Pass the current map of agents so it can find neighbors or update state
          this.conversationDirector.update(time, delta, this.agentsDataStore);
      }

      // 3. Mock Agent Simulation (Movement Interpolation)
      // This smoothing logic applies to both real and mock agents
      this.agents.forEach((sprite, id) => {
          const agentData = this.agentsDataStore.get(id);
          if (!agentData) return;

          const targetX = agentData.gridX * TILE_SIZE;
          const targetY = agentData.gridY * TILE_SIZE;

          // Smoothly interpolate position
          sprite.x = Phaser.Math.Linear(sprite.x, targetX, 0.1);
          sprite.y = Phaser.Math.Linear(sprite.y, targetY, 0.1);

          // Update depth sorting
          sprite.setDepth(sprite.y + 16);
          
          // Update nametag position
          const nameTag = this.agentNameTags.get(id);
          if (nameTag) {
              nameTag.x = sprite.x;
              nameTag.y = sprite.y - 20;
              nameTag.setDepth(sprite.depth + 100);
          }

          // Show bubble if chatting
          if (agentData.state === 'chatting') {
              // Simple visual indicator for chat state
              nameTag?.setText('💬 ' + (agentData.name || 'Agent'));
              nameTag?.setColor('#00ff88');
          } else {
              nameTag?.setText(agentData.name || 'Agent');
              nameTag?.setColor('#ffffff');
          }

          // Update shadow position
          const shadow = this.agentShadows.get(id);
          if (shadow) {
              shadow.x = sprite.x;
              shadow.y = sprite.y;
              shadow.setDepth(sprite.depth - 1);
          }
      });
  }

  /**
   * Initialize mock simulation with random agents
   */
  private startMockSimulation() {
      console.log('Starting Mock Simulation...');
      const jobs: JobRole[] = ['TECH_DEV_MALE', 'HEALTH_DOC_MALE', 'SERVICE_CHEF', 'EDU_PROFESSOR', 'CREATIVE_ARTIST'];
      
      // Create initial agents
      for (let i = 0; i < 10; i++) {
          const job = jobs[i % jobs.length];
          const charDef = getCharacterByJob(job);
          
          const agent: AgentData = {
              id: `mock-${i}`,
              name: `${charDef.name} ${i+1}`,
              bio: `A simulated ${charDef.name.toLowerCase()} entity.`,
              job: job,
              gridX: Math.floor(Math.random() * 30) + 5,
              gridY: Math.floor(Math.random() * 20) + 5,
              state: 'idle',
              color: Math.random() * 0xffffff,
              activeConversation: []
          };
          this.mockAgents.push(agent);
      }

      // Start the tick loop
      this.mockTickTimer = this.time.addEvent({
          delay: TICK_DURATION,
          loop: true,
          callback: () => this.runMockTick()
      });
      
      // Initial render
      this.handleServerTick({ tick: 0, agents: this.mockAgents });
  }

  /**
   * Run one tick of the mock simulation logic
   */
  private runMockTick() {
      this.mockAgents.forEach(agent => {
          // If chatting, don't move
          if (agent.state === 'chatting') return;

          // Random movement
          if (Math.random() > 0.8) {
              const dx = Math.floor(Math.random() * 3) - 1; // -1, 0, 1
              const dy = Math.floor(Math.random() * 3) - 1;
              
              const newX = agent.gridX + dx;
              const newY = agent.gridY + dy;

              // Check bounds and collisions
              if (this.collisionManager?.isWalkable(newX, newY)) {
                  agent.gridX = newX;
                  agent.gridY = newY;
                  agent.state = (dx !== 0 || dy !== 0) ? 'moving' : 'idle';
              }
          } else {
              agent.state = 'idle';
          }
      });

      // Send update to game loop
      this.handleServerTick({ tick: Date.now(), agents: this.mockAgents });
  }

  /**
   * Process a server update (tick)
   */
  private handleServerTick(update: WorldUpdate) {
      // Track valid IDs to remove stale sprites
      const validIds = new Set<string>();

      update.agents.forEach((agentData) => {
          validIds.add(agentData.id);
          
          // Merge with existing data to preserve client-side state like activeConversation
          // unless server sends it
          const existing = this.agentsDataStore.get(agentData.id);
          if (existing) {
              this.agentsDataStore.set(agentData.id, {
                  ...existing,
                  ...agentData,
                  // Keep conversation state if server didn't send it (mock mode handles this via director)
                  activeConversation: existing.activeConversation || agentData.activeConversation,
                  state: agentData.state // Allow server to override state
              });
          } else {
              this.agentsDataStore.set(agentData.id, agentData);
          }

          let sprite = this.agents.get(agentData.id);

          if (!sprite) {
              // Create new sprite
              const charDef = this.getCharacterForAgent(agentData);
              const texture = this.textures.exists(charDef.spriteKey) ? charDef.spriteKey : 'characters';
              const frame = this.textures.exists(charDef.spriteKey) ? charDef.frameIndex : (agentData.job ? 0 : 0); // fallback frame

              sprite = this.add.sprite(agentData.gridX * TILE_SIZE, agentData.gridY * TILE_SIZE, texture, frame);
              sprite.setOrigin(0.5, 0.5);
              sprite.setInteractive();
              sprite.on('pointerdown', () => {
                  const currentData = this.agentsDataStore.get(agentData.id);
                  if (this.onAgentSelect && currentData) this.onAgentSelect(currentData);
              });

              this.agents.set(agentData.id, sprite);

              // Add Nametag
              const nameTag = this.add.text(sprite.x, sprite.y - 20, agentData.name || 'Agent', {
                  fontSize: '10px',
                  color: '#ffffff',
                  backgroundColor: '#00000080',
                  padding: { x: 2, y: 1 }
              }).setOrigin(0.5);
              this.agentNameTags.set(agentData.id, nameTag);

              // Add Shadow
              const shadow = this.add.graphics();
              shadow.fillStyle(0x000000, 0.3);
              shadow.fillEllipse(0, 14, 20, 8);
              this.agentShadows.set(agentData.id, shadow);
          }
      });

      // Cleanup stale agents
      this.agents.forEach((sprite, id) => {
          if (!validIds.has(id)) {
              sprite.destroy();
              this.agents.delete(id);
              
              this.agentNameTags.get(id)?.destroy();
              this.agentNameTags.delete(id);

              this.agentShadows.get(id)?.destroy();
              this.agentShadows.delete(id);
              
              this.agentsDataStore.delete(id);
          }
      });
  }

  /**
   * Get character definition from agent data
   * Uses spriteKey if available, otherwise looks up by job
   */
  private getCharacterForAgent(agentData: AgentData): CharacterDefinition {
    // First check for custom spriteKey
    if (agentData.spriteKey && CHARACTER_REGISTRY[agentData.spriteKey]) {
      return CHARACTER_REGISTRY[agentData.spriteKey];
    }
    
    // Fall back to job-based lookup
    if (agentData.job) {
      return getCharacterByJob(agentData.job);
    }
    
    // Default fallback
    return getCharacterById('TECH_DEV_MALE');
  }

  /**
   * Add post-processing effects for visual polish
   * Includes: subtle vignette, color grading, and optional scanlines
   */
  private addPostProcessingEffects(): void {
    // Add subtle vignette overlay (reduced intensity)
    const width = this.cameras.main.width;
    const height = this.cameras.main.height;
    
    const vignetteGraphics = this.add.graphics();
    vignetteGraphics.setScrollFactor(0);
    vignetteGraphics.setDepth(10000);
    
    // Radial gradient vignette (lighter, less intense)
    const centerX = width / 2;
    const centerY = height / 2;
    const maxRadius = Math.sqrt(centerX * centerX + centerY * centerY);
    
    for (let radius = maxRadius; radius > 0; radius -= 10) {
      const alpha = Math.max(0, Math.min(0.2, (radius / maxRadius - 0.6) * 0.5));
      vignetteGraphics.fillStyle(0x000000, alpha * 0.15); // Reduced from 0.3 to 0.15
      vignetteGraphics.fillCircle(centerX, centerY, radius);
    }
    
    // Optional: Matrix-themed green tint (subtle)
    const tintGraphics = this.add.graphics();
    tintGraphics.setScrollFactor(0);
    tintGraphics.setDepth(9999);
    tintGraphics.fillStyle(0x00ff88, 0.01); // Reduced from 0.02 to 0.01
    tintGraphics.fillRect(0, 0, width, height);
    
    // Optional: CRT scanlines effect (lighter)
    const scanlinesGraphics = this.add.graphics();
    scanlinesGraphics.setScrollFactor(0);
    scanlinesGraphics.setDepth(9998);
    scanlinesGraphics.lineStyle(1, 0x000000, 0.02); // Reduced from 0.05 to 0.02
    
    for (let y = 0; y < height; y += 4) {
      scanlinesGraphics.lineBetween(0, y, width, y);
    }
  }

  private handleCreateAgentEvent = (event: CustomEvent<Partial<AgentData>>) => {
    const newAgent = event.detail;
    console.log("MainScene received new agent:", newAgent);
    
    // For the mock simulation, add the agent to our persistent mockAgents array
    if (this.useMockData) {
        const id = `custom-${Date.now()}`;
        const agentData: AgentData = {
            id,
            gridX: newAgent.gridX || Math.floor(Math.random() * 20) + 10,
            gridY: newAgent.gridY || Math.floor(Math.random() * 15) + 5,
            state: 'idle',
            name: newAgent.name || 'Custom Agent',
            bio: newAgent.bio || 'User generated.',
            job: newAgent.job || 'TECH_DEV_MALE',
            spriteKey: newAgent.spriteKey, // Support custom character sprites
            color: Math.random() * 0xffffff,
            lastMessage: "Hello world! I am new here.",
            activeConversation: []
        };
        
        // Add to the persistent mockAgents array
        this.mockAgents.push(agentData);
        
        console.log(`Agent "${agentData.name}" added to mock simulation. Total agents: ${this.mockAgents.length}`);
    }
  };

  private handleStartChatEvent = (event: CustomEvent<{agentId: string}>) => {
      const { agentId } = event.detail;
      const initiator = this.agentsDataStore.get(agentId);
      if (!initiator || !this.conversationDirector) return;

      // Find nearest neighbor
      let nearest: AgentData | null = null;
      let minDist = Infinity;

      this.agentsDataStore.forEach(other => {
          if (other.id === agentId) return;
          const dist = Phaser.Math.Distance.Between(initiator.gridX, initiator.gridY, other.gridX, other.gridY);
          if (dist < minDist) {
              minDist = dist;
              nearest = other;
          }
      });

      if (nearest) {
          console.log(`Starting chat between ${initiator.name} and ${nearest.name}`);
          this.conversationDirector.startConversation(initiator, nearest);
      } else {
          console.warn("No neighbor found to chat with.");
      }
  };

  private shutdownScene() {
    window.removeEventListener('create-agent', this.handleCreateAgentEvent as EventListener);
    window.removeEventListener('start-chat', this.handleStartChatEvent as EventListener);
    if (this.mockTickTimer) this.mockTickTimer.remove();
    if (this.socket) {
        this.socket.disconnect();
        this.socket = null;
    }
    
    // Cleanup environment
    if (this.environmentRenderer) {
      this.environmentRenderer.destroy();
    }
  }
      // Create a generative texture for agents if image is missing
  private createFallbackTextures() {
      // Create a generative texture for agents if image is missing
      // Passing add: false so it doesn't get added to the scene, just used for texture generation
      const graphics = this.make.graphics({ x: 0, y: 0 });
      
      // Draw 10 different colored squares as frames
      for (let i = 0; i < 10; i++) {
          graphics.fillStyle(0xffffff, 1);
          graphics.fillRect(i * 32, 0, 32, 32);
          graphics.fillStyle(Math.random() * 0xffffff, 1);
          graphics.fillRect(i * 32 + 4, 4, 24, 24);
          // Eyes
          graphics.fillStyle(0x000000, 1);
          graphics.fillRect(i * 32 + 8, 10, 4, 4);
          graphics.fillRect(i * 32 + 20, 10, 4, 4);
      }
      
      try {
          graphics.generateTexture('characters', 320, 32);
          
          // Manually add frames to the new texture
          if (this.textures.exists('characters')) {
              for (let i = 0; i < 10; i++) {
                  this.textures.get('characters').add(i, 0, i * 32, 0, 32, 32);
              }
          }
      } catch (e) {
          console.error("Failed to generate fallback texture:", e);
      } finally {
          graphics.destroy();
      }
  }

  private createWorld() {
    // World dimensions
    const width = 40; // grid units
    const height = 30;
    
    // Initialize Environment Manager with a fixed seed for deterministic generation
    const seed = 12345;
    this.environmentManager = new EnvironmentManager(width, height, seed);
    const environment = this.environmentManager.generateEnvironment();

    // Initialize Collision Manager
    this.collisionManager = new CollisionManager(this.environmentManager);

    // Initialize Environment Renderer
    this.environmentRenderer = new EnvironmentRenderer(this, seed);
    
    // Render the complete environment
    this.environmentRenderer.render(
      width, 
      height, 
      environment.buildings, 
      environment.plants
    );
    
    // Set world bounds
    this.cameras.main.setBounds(0, 0, width * TILE_SIZE, height * TILE_SIZE);
  }

  private getAuthToken(): string | null {
    return sessionStorage.getItem('auth_token');
  }

  private validateSocketUrl(url: string): boolean {
    try {
      const parsed = new URL(url);
      // Only allow ws:// or wss://
      return parsed.protocol === 'ws:' || parsed.protocol === 'wss:';
    } catch {
      return false;
    }
  }

  private setupSocket() {
    // Safely access environment variables with fallback
    const meta = import.meta as any;
    const env = meta.env || {};
    const isProduction = env.PROD === true;
    
    const defaultUrl = env.DEV 
      ? 'ws://localhost:3000' 
      : 'wss://api.yourdomain.com';
    
    const url = env.VITE_SOCKET_URL || defaultUrl;
    
    // Validate URL format
    if (!this.validateSocketUrl(url)) {
      console.error('Invalid socket URL format, falling back to default');
    }

    if (isProduction && !url.startsWith('wss://')) {
        // throw new Error('Secure WebSocket (WSS) required in production'); // Softened for demo
        console.warn('Production should use WSS');
    }
    
    const token = this.getAuthToken();

    this.socket = io(url, {
      transports: ['websocket'],
      autoConnect: true,
      reconnectionAttempts: 3,
      auth: {
        token: token || undefined, // Send token if available
      },
    });

    this.socket.on('connect', () => {
      if (env.DEV) console.log('Connected to backend');
      this.useMockData = false; // Disable mock if real server connects
      if (this.mockTickTimer) this.mockTickTimer.remove();
      this.socket?.emit('join_world');
      
      // Pass socket to Director
      if (this.conversationDirector) {
          this.conversationDirector.setSocket(this.socket);
      }
    });

    this.socket.on('disconnect', () => {
      console.log('Disconnected from backend');
      // Fallback to mock mode
      this.useMockData = true;
      if (this.conversationDirector) {
          this.conversationDirector.setSocket(null);
      }
      this.startMockSimulation();
    });

    this.socket.on('server_tick', (update: WorldUpdate) => {
      this.handleServerTick(update);
    });
  }
  
  private createZoomIndicator() {
    this.zoomUI = this.add.text(10, 10, `Zoom: ${this.currentZoom.toFixed(1)}x`, {
      fontSize: '16px',
      color: '#ffffff',
      backgroundColor: '#00000080'
    })
    .setScrollFactor(0)
    .setDepth(10000);
  }

  private setZoom(zoom: number) {
    this.currentZoom = Phaser.Math.Clamp(zoom, this.minZoom, this.maxZoom);
    this.cameras.main.zoomTo(this.currentZoom, 100, 'Linear', true);
    if (this.zoomUI) {
      this.zoomUI.setText(`Zoom: ${this.currentZoom.toFixed(1)}x`);
    }
  }

  private setupInput() {
    this.input.on('pointerdown', (pointer: Phaser.Input.Pointer) => {
        const touchStartX = pointer.x;
        const touchStartY = pointer.y;
        const camStartX = this.cameras.main.scrollX;
        const camStartY = this.cameras.main.scrollY;

        this.input.on('pointermove', (p: Phaser.Input.Pointer) => {
             if (!p.isDown) return;
             this.cameras.main.scrollX = camStartX + (touchStartX - p.x) / this.cameras.main.zoom;
             this.cameras.main.scrollY = camStartY + (touchStartY - p.y) / this.cameras.main.zoom;
        });
    });
  }

  private setupZoomControls(): void {
    this.input.on('wheel', (pointer: Phaser.Input.Pointer, gameObjects: Phaser.GameObjects.GameObject[], deltaX: number, deltaY: number) => {
      const zoomDelta = deltaY > 0 ? -this.zoomSpeed : this.zoomSpeed;
      this.setZoom(this.currentZoom + zoomDelta);
    });

    if (this.input.keyboard) {
      this.input.keyboard.on('keydown', (event: KeyboardEvent) => {
        if (event.key === '+' || event.key === '=') {
          this.setZoom(this.currentZoom + this.zoomSpeed);
        } else if (event.key === '-' || event.key === '_') {
          this.setZoom(this.currentZoom - this.zoomSpeed);
        }
      });
    }
    this.createZoomIndicator();
  }
}